### ISSUE TITLE
about std buffer

### ISSUE THREAD

**Issue by Blues-star** [hoferand/fiter#1]
I have a question, I haven't looked into the iteration over ASCII strings and UTF-8 strings in std, but I noticed that it's faster than fiter for a 1k buffer. How large is the buffer in std, or is it implemented in a different way?

**Comment by hoferand** [comment]
The iterator using the std lib is the following:
```rust
read_to_string(&file).unwrap().chars()
```
The `read_to_string()` reads the entire file content into a string and allocates as much memory as needed. So if the file is 1MB big the function allocates 1MB on the heap for that.
